// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypmjwzbcebhyqwdagdde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwbWp3emJjZWJoeXF3ZGFnZGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzkzMTQsImV4cCI6MjA2MzQxNTMxNH0.cprZJ8XEGrgg-l-AVgdEmQ0aOz1BbmGzBG76PEzv52M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);